In [2]:
import numpy as np
import pandas as pd

%matplotlib inline

In [3]:
def sigmoid(x):
    return 1/(1+np.exp(-x))


def nn_prob(shot_data):
    theta1 = np.load('./Neural Net/xG_theta1.npy')
    theta2 = np.load('./Neural Net/xG_theta2.npy')
    X_cv = shot_data.as_matrix(columns=['x', 'y', 'Header',
                                        'Distance', 'Angle'])

    X_cv = np.c_[np.ones(X_cv.shape[0]), X_cv]

    m = X_cv.shape[0]

    a_1 = X_cv.T
    z_2 = np.dot(theta1, a_1)
    a_2 = sigmoid(z_2)
    # WILL ADD A BIAS UNIT SOON
    z_3 = np.dot(theta2, a_2)
    a_3 = sigmoid(z_3)
    h_theta = a_3
    return h_theta.T

def tidy_and_format_data(shot_data):
    '''
    takes shot data, adds distance, angle, colour and a probability
    :param shot_data:
    :return:
    '''
    for index, row in shot_data.iterrows():
        if row['x'] > 240:
            shot_data.set_value(index, 'x', 480 - row['x'])

    shot_data['y'] = shot_data['y'] - 366/2
    shot_data['y'] = shot_data['y'] * -1
    # calculate the angle and the distance from the goal
    shot_data['Angle'] = np.arctan((np.absolute(shot_data['y'])/shot_data['x']))
    shot_data['Distance'] = np.sqrt(shot_data['y']*shot_data['y'] + shot_data['x']*shot_data['x'])

    # assign colours and numbers based on whether the shots were scored or missed
    for index, row in shot_data.iterrows():
        if row['Scored'] == 'Scored':
            shot_data.set_value(index, 'Colour', 'magenta')
            shot_data.set_value(index, 'ScoredBinary', 1)
        else:
            shot_data.set_value(index, 'Colour', 'white')
            shot_data.set_value(index, 'ScoredBinary', 0)

    shot_data['Proba_exp'] = nn_prob(shot_data)

    return shot_data

In [4]:
data = pd.read_csv('./All shots from 17-18/E0/shots.csv', index_col=0)
football_data = pd.read_csv('./Football-data.co.uk/E0/17-18.csv')
football_data['Date'] = pd.to_datetime(football_data['Date'], format='%d/%m/%y')
data['Date'] = pd.to_datetime(data['Date'], format='%d-%m-%Y')
mappings = pd.read_csv('./All shots from 17-18/E0/mappings.csv', index_col=1, header=None)
data.replace(mappings[0], inplace=True)

data = tidy_and_format_data(data) # add xG values to each shot and a colour etc

In [29]:
new = data.groupby(['PlayerID'], as_index=False)['Proba_exp', 'ScoredBinary'].sum()

In [30]:
new.head()

   PlayerID  Proba_exp  ScoredBinary
0        61   1.412531           2.0
1        73   1.134248           2.0
2        77   1.983791           1.0
3        81   0.042842           0.0
4        84   0.329336           0.0

In [31]:
new.sort_values('ScoredBinary', ascending=False, inplace=True)
new.head()

     PlayerID  Proba_exp  ScoredBinary
90        897   5.572367           7.0
118      1847   2.487162           6.0
79        856   5.176293           6.0
239     10705   3.621200           5.0
49        564   3.836699           5.0

In [35]:
player_map = data[['PlayerID', 'PlayerName']]
player_map.drop_duplicates(subset='PlayerID', keep='first', inplace=True)
player_map.set_index('PlayerID', drop=True, inplace=True)

/usr/local/lib/python2.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [36]:
player_dict = player_map.to_dict()
player_dict

{'PlayerName': {61: 'Eriksen',
  73: 'Wayne Rooney',
  77: 'Defoe',
  81: 'Ashley Young',
  84: 'Milner',
  86: 'Jordan Hende',
  87: 'Andy Carroll',
  88: 'Welbeck',
  89: 'Phil Jones',
  90: 'Oxlade-Chamb',
  91: 'Martin Kelly',
  111: 'Cabaye',
  113: 'Koscielny',
  115: 'Giroud',
  123: '\xc3\x96zil',
  136: 'Ilkay G\xc3\xbcndog',
  160: 'Holebas',
  206: '206',
  263: 'Shane Long',
  271: 'Stephen Ward',
  272: 'Jonathan Wal',
  275: 'McClean',
  306: 'F\xc3\xa0bregas',
  308: 'David Silva',
  313: 'Juan Mata',
  320: 'Rodr\xc3\xadguez Le',
  342: 'Martin Olsso',
  374: 'Kieran Gibbs',
  377: 'Ramsey',
  380: 'Coquelin',
  382: 'Kyle Bartley',
  411: 'Ciaran Clark',
  413: 'Albrighton',
  414: 'Delph',
  429: 'Lowton',
  437: 'Bertrand',
  441: 'Sturridge',
  446: 'Chalobah',
  448: 'Luiz Moreira',
  449: 'Romeu Vidal',
  454: 'Eden Hazard',
  466: 'Fellaini',
  471: 'Shane Duffy',
  493: 'Mousa Demb\xc3\xa9l',
  523: 'Shelvey',
  534: 'Raheem Sterl',
  540: 'Joe Allen',
  543: 'Kompany',
  546: 'Gareth Barry',
  564: 'Ag\xc3\xbcero',
  572: 'Darren Fletc',
  574: 'Jonny Evans',
  576: 'Cleverley',
  581: 'Antonio Vale',
  582: 'Joshua King',
  583: 'Hern\xc3\xa1ndez Ba',
  584: 'Smalling',
  587: 'Robbie Brady',
  592: 'Michael Kean',
  642: 'Surman',
  697: 'Robson-Kanu',
  720: 'Mariappa',
  724: 'Schneiderlin',
  729: 'Jos\xc3\xa9 Fonte',
  732: 'Puncheon',
  738: 'Jack Stephen',
  739: 'Ward-Prowse',
  743: 'Cork',
  750: 'Jay Rodrigue',
  753: 'Steven Davis',
  758: 'Shawcross',
  773: 'Crouch',
  778: 'Geoff Camero',
  810: 'Ashley Willi',
  831: 'Ben Davies',
  840: 'Aaron Lennon',
  846: 'Livermore',
  851: 'Andros Towns',
  854: '854',
  856: 'Harry Kane',
  861: 'Tom Carroll',
  863: 'Gylfi Sigurd',
  864: 'Vertonghen',
  865: 'Adam Smith',
  868: 'James Morris',
  869: 'Chris Brunt',
  871: 'Chris Wood',
  884: 'Craig Dawson',
  886: 'Berahino',
  896: 'Yacob',
  897: 'Romelu Lukak',
  898: 'Mark Noble',
  900: 'Tomkins',
  905: 'Winston Reid',
  922: 'Mohamed Diam',
  925: 'James Collin',
  936: 'Moses',
  940: 'McArthur',
  1098: 'Idrissa Guey',
  1151: 'Alexandre La',
  1156: 'Lovren',
  1174: 'Andr\xc3\xa9 Ayew',
  1180: '1180',
  1182: 'Azpilicueta',
  1294: 'Mamadou Sakh',
  1335: 'Krychowiak',
  1370: 'Abdoulaye Do',
  1410: 'Sako',
  1419: 'Kurt Zouma',
  1434: 'Moussa Sisso',
  1436: 'Capoue',
  1455: 'Aurier',
  1538: '1538',
  1581: 'Alexis S\xc3\xa1nch',
  1683: 'Nyom',
  1722: 'G\xc3\xa1mez Duarte',
  1736: 'Monreal',
  1753: 'Hemed',
  1847: 'Morata',
  2000: 'Choupo-Motin',
  2021: 'Roberto Firm',
  2028: 'Danny Willia',
  2042: 'Mato Sanmart',
  2074: 'Chris L\xc3\xb6we',
  2103: 'Granit Xhaka',
  2169: 'Emre Can',
  2172: 'Shaqiri',
  2178: 'Joel Matip',
  2191: 'Christian Fu',
  2196: 'Kolasinac',
  2241: 'Son',
  2277: 'Mame Biram D',
  2354: 'Okazaki',
  2359: 'R\xc3\xbcdiger',
  2408: 'Arnautovic',
  2431: 'De Bruyne',
  2441: 'Gabbiadini',
  2610: 'Hegazi',
  2673: 'Philippe Cou',
  2710: 'Paul Pogba',
  2809: 'Miguel Brito',
  2911: 'Okaka',
  2921: 'Krkic Perez',
  2948: 'Pedro Obiang',
  2963: 'Mustafi',
  3013: 'Darmian',
  3049: 'Roberto Pere',
  3272: 'Sadio Man\xc3\xa9',
  3613: 'Dann',
  3632: 'Lee Chung-yo',
  3635: 'Marcos Alons',
  3655: 'Afobe',
  3728: 'Manquillo',
  3732: 'Yoshida',
  3738: 'Christian Be',
  3832: 'Beller\xc3\xadn',
  3837: 'Lingard',
  3926: 'Anthony Mart',
  4029: 'Ak\xc3\xa9',
  4094: 'Alberto More',
  4112: 'Lemina',
  4188: '4188',
  4207: 'Stones',
  4299: 'Ibe',
  4807: 'Yedlin',
  4902: 'Andreas Chri',
  4920: 'Loftus-Cheek',
  4942: 'Zaha',
  4949: 'van Aanholt',
  4958: 'Luiz Rosa',
  5187: 'Joel Ward',
  5195: 'Glenn Murray',
  5228: 'Rosenior',
  5493: 'Dwight Gayle',
  5496: 'Nathan Redmo',
  5558: 'Benjamin Men',
  5563: 'Mkhitaryan',
  5573: 'Wanyama',
  5574: 'Bony',
  5643: 'Femen\xc3\xada Far',
  7109: 'Rodr\xc3\xadguez Ru',
  7145: 'Borges Da Si',
  7342: 'Rond\xc3\xb3n',
  7666: 'Klaassen',
  7669: 'van der Hoor',
  7673: 'Alderweireld',
  7674: 'Blind',
  7682: 'Hoedt',
  7689: 'Berg Gudmund',
  7763: 'Dusan Tadic',
  7818: 'Martins Indi',
  7831: 'Janmaat',
  7968: 'Georginio Wi',
  7969: 'Zanka',
  8088: 'van La Parra',
  8105: 'Davy Pr\xc3\xb6pper',
  8197: 'Tiemou\xc3\xa9 Baka',
  8206: 'Mounie',
  8331: 'Atsu',
  9093: 'Batshuayi',
  9245: 'Elneny',
  9258: 'Mohamed Sala',
  9284: 'Nemanja Mati',
  9297: 'Virgil van D',
  9350: 'Otamendi',
  9356: 'Danilo',
  9360: 'Defour',
  9394: 'Suttner',
  9425: 'Nordin Amrab',
  9453: 'Milivojevic',
  9470: 'Kouyat\xc3\xa9',
  9471: 'Aleksandar M',
  9548: '9548',
  9578: 'Iwobi',
  9872: 'Riedewald',
  10014: 'Demarai Gray',
  10072: 'Tom Ince',
  10148: 'Simon Franci',
  10150: 'Steve Cook',
  10162: 'Marc Pugh',
  10164: 'Harry Arter',
  10166: 'Charlie Dani',
  10174: 'Ryan Fraser',
  10182: 'Matt Ritchie',
  10212: 'Lewis Dunk',
  10234: 'Solly March',
  10238: 'Ashley Barne',
  10256: 'Kieran Tripp',
  10264: 'Ben Mee',
  10282: 'Junior Stani',
  10292: 'Scott Arfiel',
  10300: 'Sam Vokes',
  10340: 'Dale Stephen',
  10408: 'Jeff Hendric',
  10504: 'Tommy Smith',
  10560: 'Aaron Cressw',
  10686: 'Wes Morgan',
  10694: 'Matty James',
  10695: 'Andy King',
  10705: 'Vardy',
  10707: 'Jeffrey Schl',
  10715: 'Anthony Knoc',
  10853: 'Jamaal Lasce',
  10899: 'Matt Phillip',
  10903: 'Charlie Aust',
  10955: 'Michail Anto',
  11010: 'Troy Deeney',
  11309: 'Mooy',
  11399: '11399',
  11509: 'Mahrez',
  12319: 'Leroy San\xc3\xa9',
  12372: 'Billing',
  12606: 'Veiga de Car',
  12669: 'Slimani',
  14359: 'Andr\xc3\xa9 Carril',
  14538: 'Robertson',
  14999: "N'Golo Kant\xc3\xa9",
  15035: 'Diafra Sakho',
  15144: 'P\xc3\xa9rez Guti\xc3\xa9r',
  15160: 'Tarkowski',
  15161: '15161',
  15177: 'Andre Gray',
  15280: 'Kachunga',
  15466: 'Solanke',
  15510: 'Iheanacho',
  15533: 'Harry Maguir',
  15553: 'Dier',
  15595: 'Sandro Ram\xc3\xadr',
  15657: 'Zappacosta',
  15786: 'Lewis Cook',
  15806: 'Oumar Niasse',
  16192: 'C\xc3\xa9dric Soare',
  16317: 'Izquierdo Me',
  16605: 'Eric Bailly',
  16633: 'Oliver Burke',
  17351: 'Boufal',
  18137: 'Gabriel Jesu',
  18185: 'Alli',
  18311: 'Lanzini',
  18316: 'Alexander-Ar',
  18343: 'Clucas',
  18466: 'Holding',
  18702: 'Gro\xc3\x9f',
  18852: 'Jamie Murphy',
  18890: 'Roque Mesa',
  19189: 'Depoitre',
  19300: 'Edimilson Fe',
  19695: 'Luz Sanches',
  19728: 'Rashford',
  20160: '-Fosu-Mensah',
  20368: 'Kasey Palmer',
  20389: 'Tom Davies',
  20451: 'Tammy Abraha',
  20573: 'Richarlison',
  20816: 'Mousset',
  20871: 'Schindler',
  21082: '21082',
  21942: 'Ndidi',
  22275: 'Calvert-Lewi',
  22827: 'Quaner',
  23637: 'Sabiri',
  24006: 'Vlasic',
  24042: 'Lumeka'}}

In [37]:
new.replace(player_dict['PlayerName'], inplace=True)

In [26]:
new.set_index('PlayerID', drop=True, inplace=True)

In [38]:
new.to_csv('players.csv')

         PlayerID  Proba_exp  ScoredBinary
90   Romelu Lukak   5.572367           7.0
118        Morata   2.487162           6.0
79     Harry Kane   5.176293           6.0
239         Vardy   3.621200           5.0
49         Agüero   3.836699           5.0
45   Raheem Sterl   2.944009           5.0
99   Alexandre La   3.124712           4.0
276  Gabriel Jesu   2.555697           4.0
201  Mohamed Sala   3.331386           4.0
147    Sadio Mané   1.934727           3.0
7         Welbeck   2.236512           3.0
55   Hernández Ba   1.952511           3.0
293   Richarlison   2.736695           3.0
157  Anthony Mart   1.228217           3.0
250    Leroy Sané   1.150211           3.0
106  Abdoulaye Do   0.816386           3.0
41       Fellaini   1.775232           3.0
132       Okazaki   2.217475           3.0
270  Oumar Niasse   1.016492           2.0
71         Crouch   0.859219           2.0

In [6]:
meanxg = data.groupby(['PlayerID'], as_index=False)['Proba_exp'].mean().sort_values('Proba_exp', ascending=False)

In [7]:
meanxg

     PlayerID  Proba_exp
8          89   0.478478
94        922   0.459438
41        466   0.443808
190      7818   0.370478
273     16605   0.365728
127      2178   0.354473
51        574   0.343033
299     22827   0.331167
281     18466   0.305082
151      3655   0.293693
87        884   0.292334
141      2911   0.290885
71        773   0.286406
132      2354   0.277184
153      3732   0.274351
264     15510   0.272734
244     10903   0.270742
2          77   0.247974
263     15466   0.246390
75        840   0.244614
239     10705   0.241413
88        886   0.237145
31        411   0.224475
30        382   0.224203
265     15533   0.223130
101      1174   0.212331
10         91   0.208049
84        868   0.205669
211      9471   0.203659
232     10340   0.201194
..        ...        ...
168      4949   0.026852
11        111   0.026826
53        581   0.026620
128      2191   0.026533
145      3013   0.026101
234     10504   0.025535
91        898   0.025284
78        854   0.024878
221     10166   0.024169
284     18890   0.023986
34        429   0.023499
220     10164   0.023455
272     16317   0.023316
191      7831   0.023237
114      1683   0.023231
164      4807   0.023217
274     16633   0.022855
179      5643   0.022502
143      2948   0.022236
251     12372   0.021808
16        160   0.021717
209      9453   0.021400
207      9394   0.021211
287     19695   0.021081
105      1335   0.021042
26        342   0.020707
278     18311   0.020539
133      2359   0.020326
289     20160   0.019575
123      2074   0.017604

[303 rows x 2 columns]